### ISSUE TITLE
example json file needs abbreviation in units

### ISSUE THREAD

**Issue by nickreich** [reichlab/docs.zoltardata#13]
This file https://github.com/reichlab/docs.zoltardata/blob/master/docs/zoltar-project-config.json
does not comport with the required "abbreviation" field needed in units, per documentation here: https://docs.zoltardata.com/fileformats/#project-creation-configuration-json

**Comment by nickreich** [comment]
Also, I think the "unit" field in the targets section is not valid either. Per description on this page, "unit" is not a valid field name for a target, and yet it is present in the config file above.

**Comment by matthewcornell** [comment]
This should do it: [updated out-of-date zoltar-project-config.json](https://github.com/reichlab/docs.zoltardata/commit/e2ee43a7721f9c513546074bb3eecced9587d454)
