### ISSUE TITLE
integrate documentation from zoltr pkgdown site

### ISSUE THREAD

**Issue by nickreich** [reichlab/docs.zoltardata#4]
need to figure out most efficient way to do this.

**Comment by mzorn-58** [comment]
@nickreich Can this be closed?

**Comment by matthewcornell** [comment]
Not sure what this is addressing. Currently we have https://docs.zoltardata.com/zoltr/ , which does point to the pkgdown site: http://reichlab.io/zoltr/ . Does "integrate" mean something different?

**Comment by mzorn-58** [comment]
@nickreich Can you reply to Matt?
